site_name: European Digital Identity
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - toc.integrate
    - toc.follow
  logo: assets/logo_eudi_white.svg
  favicon: assets/favicon.ico

extra_css:
  - css/extra.css

markdown_extensions:
  - footnotes
  - sane_lists
  - tables

site_url: https://eu-digital-identity-wallet.github.io
repo_url: https://github.com/eu-digital-identity-wallet/eudi-doc-developers-hub-site
repo_name: eu-digital-identity-wallet/eudi-doc-developers-hub-site

nav:
  - European Digital Identity Wallet: https://eudi.dev/latest/
  - Architecture and reference framework: https://eudi.dev/latest/architecture-and-reference-framework-main/
  - Discussion topics: https://eudi.dev/latest/discussion-topics/
  - Technical specifications: https://eudi.dev/latest/technical-specifications/
  - Reference Implementation:
      - Overview: 
          - Introduction: index.md
          - Feature Map: feature-map.md
          - Roadmap: roadmap.md
          - Repositories List: repositories-list.md
          - Quality Assurance: quality-assurance.md
      - Build:
          - Introduction: Build/index.md
          - Build your Wallet:
              - Build your Wallet: Build/Build your Wallet/index.md
              - Android:
                  - Wallet Application Level:
                      - Build the App: Build/Build your Wallet/Android/Wallet Application Level/index.md
                      - Run with Remote Services: Build/Build your Wallet/Android/Wallet Application Level/Running with Remote Services.md
                      - Run with Local Services: Build/Build your Wallet/Android/Wallet Application Level/Running with Local Services.md
                      - Self-signed Certificates: Build/Build your Wallet/Android/Wallet Application Level/Self-signed Certificates.md
                  - Library Level:
                      - Library Level: Build/Build your Wallet/Android/Library Level/index.md
                      - Build the Core: Build/Build your Wallet/Android/Library Level/Build the Core.md
                      - Manage Documents: Build/Build your Wallet/Android/Library Level/Manage Documents.md
              - iOS:
                  - Wallet Application Level:
                      - Build the App: Build/Build your Wallet/iOS/Wallet Application Level/index.md
                      - Run with Remote Services: Build/Build your Wallet/iOS/Wallet Application Level/Running with Remote Services.md
                      - Run with Local Services: Build/Build your Wallet/iOS/Wallet Application Level/Running with Local Services.md
                      - Self-signed Certificates: Build/Build your Wallet/iOS/Wallet Application Level/Self-signed Certificates.md
                  - Library Level:
                      - Library Level: Build/Build your Wallet/iOS/Library Level/index.md
                      - Build the Kit: Build/Build your Wallet/iOS/Library Level/Build the Kit.md
                      - Manage Documents: Build/Build your Wallet/iOS/Library Level/Manage Documents.md
          - Build your Issuer:
              - Overview: Build/Build your Issuer/index.md
              - Steps to Build: Build/Build your Issuer/Steps to Build.md
              - Configure your Issuer: Build/Build your Issuer/Configure.md
              - Add Attestations: Build/Build your Issuer/New Attestation.md
          - Build your Remote Verifier:
              - Overview: Build/Build your Remote Verifier/index.md
              - Steps to Build: Build/Build your Remote Verifier/Steps to Build.md
              - Configure your Verifier: Build/Build your Remote Verifier/Configure.md 
          - Build your Proximity Verifier:
              - Overview: Build/Build your Proximity Verifier/index.md
              - Build your Proximity Verifier App for Android: Build/Build your Proximity Verifier/Build your Proximity Verifier App for Android.md
              - Build your Proximity Verifier Core for Android: Build/Build your Proximity Verifier/Build your Proximity Verifier Core for Android.md
          - Build your rQES:
              - Overview: Build/Build your rQES/index.md
              - Build your rQES SDK UI for Android: Build/Build your rQES/Build your rQES SDK UI for Android.md
              - Build your rQES Core for Android: Build/Build your rQES/Build your rQES Core for Android.md
              - Build your rQES SDK UI for iOS: Build/Build your rQES/Build your rQES SDK UI for iOS.md
              - Build your rQES Kit for iOS:  Build/Build your rQES/Build your rQES Kit for iOS.md
          - Supporting Ecosystem Services:
              - Overview: Build/Supporting Ecosystem Services/index.md
              - Trust List Service: Build/Supporting Ecosystem Services/Trust List Service.md
              - RSSP: Build/Supporting Ecosystem Services/RSSP.md
              - Revocation Service: Build/Supporting Ecosystem Services/Revocation Service.md
              - RP Registration Service: Build/Supporting Ecosystem Services/RP Registration Service.md
      - Test:
          - Introduction: Test/index.md
          - Wallet Application:
              - Wallet Application: Test/Wallet Application/index.md
              - Android: Test/Wallet Application/Android.md
              - iOS: Test/Wallet Application/iOS.md
          - Issuer: Test/Issuer.md
          - Online Verifier: Test/Online Verifier.md
          - Proximity Verifier: Test/Proximity Verifier.md
      - Use Cases:
          - Mobile Driving License:
              - Mobile Driving License: use-cases/mobile-driving-license/index.md
              - mDL Overview:
                  - mDL Overview: use-cases/mobile-driving-license/mdl-overview/index.md
                  - Legal Basis: use-cases/mobile-driving-license/mdl-overview/legal-basis.md
                  - Standards and Protocols: use-cases/mobile-driving-license/mdl-overview/standards-and-protocols.md
              - mDL Architecture:
                  - mDL Architecture: use-cases/mobile-driving-license/mdl-architecture/index.md
                  - EUDI Wallet: use-cases/mobile-driving-license/mdl-architecture/eudi-wallet.md
                  - Proximity Verifier: use-cases/mobile-driving-license/mdl-architecture/proximity-verifier.md
                  - Remote Verifier Web: use-cases/mobile-driving-license/mdl-architecture/remote-verifier-web.md
                  - mDL Issuing Authority: use-cases/mobile-driving-license/mdl-architecture/mdl-issuing-authority.md
              - mDL Guides:
                  - Wallet Provider:
                      - Getting Started: use-cases/mobile-driving-license/mdl-guides/wallet-provider/getting-started.md
                      - Wallet Developers Workflow: use-cases/mobile-driving-license/mdl-guides/wallet-provider/wallet-developers-workflow.md
                      - Wallet Provider Specs: use-cases/mobile-driving-license/mdl-guides/wallet-provider/wallet-provider-specs.md
                  - mDL Issuer:
                      - Getting Started: use-cases/mobile-driving-license/mdl-guides/mdl-issuer/getting-started.md
                      - mDL Issuance Workflow: use-cases/mobile-driving-license/mdl-guides/mdl-issuer/mdl-issuance-workflow.md
                      - mDL Issuer Specs: use-cases/mobile-driving-license/mdl-guides/mdl-issuer/mdl-issuer-specs.md
                      - mDL Revocation Specs: use-cases/mobile-driving-license/mdl-guides/mdl-issuer/mdl-revocation-specs.md
                  - mDL Verifier: 
                      - Getting Started: use-cases/mobile-driving-license/mdl-guides/mdl-verifier/getting-started.md
                      - mDL Verifier Workflow: use-cases/mobile-driving-license/mdl-guides/mdl-verifier/mdl-verifier-workflow.md
                      - mDL Reader Specs: use-cases/mobile-driving-license/mdl-guides/mdl-verifier/mdl-reader-specs.md
                      - mDL Remote Verifier Specs: use-cases/mobile-driving-license/mdl-guides/mdl-verifier/mdl-remote-verifier-specs.md

extra:
  version:
    provider: mike
    alias: true

plugins:
  - mike
  - tags
  - privacy
  - social
